# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e46e4cf0ce93be702d7da36d7d69ad019985770cd6f1aa5f163f3534aa7686df4ed50eae4c44e5c6c44484e4e365ebcfac0ec5cf5b835dbc39bb6b19498086ac

test:
  secret_key_base: 0fdec254c80c5e64527a4855d664df548ed3f2d712922ff5730c53d83fc91f76d449d0497e08e9fc54cbf8c60e243f16bf3a498a162c7b05007c94b6513227b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
